# Generated by Django 5.2.7 on 2025-11-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('record_type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10)),
                ('category', models.CharField(choices=[('식비', '식비'), ('교통', '교통'), ('쇼핑', '쇼핑'), ('생활', '생활'), ('월급', '월급'), ('기타', '기타')], max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
